spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.156.115:3306/GDIP
    username: xiaoli
    password: abC123456@

  redis:
    host: 159.75.156.115
    port: 6389
    password: abC123456@
    database: 5
  data:
    mongodb:
      host: 114.132.67.226
      port: 27017
      database: mydatabase


server:
  port: 8089

