spring:
  profiles:
    active: local

wx:
  miniapp:
    configs:
      - appid: wxb53fb342651c6c2a
        secret: 6b9e4c65c7e531285e98e894b39afe6a
        token: xiaoligongzuoshi
        aesKey: xiaoligongzuoshi
        msgDataFormat: JSON

  pay:
    appId: wxb53fb342651c6c2a
    mchId: 1652632090
    mchKey: on8rr08djaowyr9hyqfivsu1taxcpjs9
    keyPath: classpath:new.p12
callback:
  success-address: "https://xiaoligongzuoshi.top/wxpay/notify"
  refund-address: "https://xiaoligongzuoshi.top/wxpay/refundNotify"



course:
  course-address: "http://cuuemo.cn:5000/handle_kb"

verify-address:
  verify-address: "http://cuuemo.cn:5000/login"
  verify-address-new: "http://cuuemo.cn:5000/login"

oss:
  endpoint: https://guangxiaoqing.com:9000
  access-key: XNQOMIJA60VZCA76WLMW
  secret-key: 8dfi1yHcvo7OI5MOgtM+OPwQGNwfuzRaFEhiWdGj