spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qing
    username: root
    password: abC123456@

  redis:
    host: localhost
    port: 6389
    password: abC123456@
    database: 0
  data:
    mongodb:
      host: 114.132.67.226
      port: 27017
      database: course

server:
  port: 443
  ssl:
    key-store: classpath:prod.pfx
    key-store-password: wkhp58w00b1
    key-store-type: PKCS12

