spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.156.115:3306/qing
    username: root
    password: abC123456@

  redis:
    host: 159.75.156.115
    port: 6379
    password: abC123456@
    database: 0
  data:
    mongodb:
      host: 114.132.67.226
      port: 27017
      database: course

server:
  port: 443
  ssl:
    key-store: classpath:guangxiaoqing.com.pfx
    key-store-password: r54ru4fjw21k0u8
    key-store-type: PKCS12

wx:
  miniapp:
    configs:
      - appid: wxb53fb342651c6c2a
        secret: 6b9e4c65c7e531285e98e894b39afe6a
        token: xiaoligongzuoshi
        aesKey: xiaoligongzuoshi
        msgDataFormat: JSON

  pay:
    appId: wxb53fb342651c6c2a
    mchId: 1652632090
    mchKey: on8rr08djaowyr9hyqfivsu1taxcpjs9
    keyPath: classpath:new.p12

callback:
  success-address: "https://guangxiaoqing.com/wxpay/notify"
  refund-address: "https://guangxiaoqing.com/wxpay/refundNotify"

qiniu:
  access-key: Y29YcvXWUe4k3Su0A63ziWxe86XTHLbcgx0-51Ke
  domain: yun.xiaoligongzuoshi.top
  bucket-name: xiaoli2023
  secret-key: qjQcw6AbtcsX1LqcAu1E1bUBUMT3L9Yt1S2Ysxo6

course:
  course-address: "http://cuuemo.cn:5000/handle_kb"

verify-address:
  verify-address: "http://cuuemo.cn:5000/login"
  verify-address-new: "http://cuuemo.cn:5000/login"

oss:
  endpoint: http://159.75.156.115:9000
  access-key: admin
  secret-key: admin123456