wx:
  miniapp:
    configs:
      - appid: wxb53fb342651c6c2a
        secret: 6b9e4c65c7e531285e98e894b39afe6a
        token: xiaoligongzuoshi
        aesKey: xiaoligongzuoshi
        msgDataFormat: JSON

  pay:
    appId: wxb53fb342651c6c2a
    mchId: 1652632090
    mchKey: on8rr08djaowyr9hyqfivsu1taxcpjs9
    keyPath: classpath:new.p12

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.67.226:3306/test
    username: xiaoli
    password: abC123456@

  redis:
    host: 114.132.67.226
    port: 6379
    password: abC123456@
    database: 1
  data:
    mongodb:
      host: 114.132.67.226
      port: 27017
      database: mydatabase


server:
  port: 8089

callback:
  success-address: "https://xiaoligongzuoshi.top/wxpay/notify"
  refund-address: "https://xiaoligongzuoshi.top/wxpay/refundNotify"

qiniu:
  access-key: Y29YcvXWUe4k3Su0A63ziWxe86XTHLbcgx0-51Ke
  domain: yun.xiaoligongzuoshi.top
  bucket-name: xiaoli2023
  secret-key: qjQcw6AbtcsX1LqcAu1E1bUBUMT3L9Yt1S2Ysxo6

course:
  course-address: "http://cuuemo.cn:5000/handle_kb"

verify-address:
  verify-address: "http://cuuemo.cn:5000/login"
  verify-address-new: "http://cuuemo.cn:5000/login"
