spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.43.168:3306/qing
    username: root
    password: abC123456!

  redis:
    host: 8.130.43.168
    port: 6379
    password: 123456
    database: 5

wx:
  miniapp:
    configs:
      - appid: wx4854ec3bcdf16e3f
        secret: e66b65f3f3b7174603ff5302ae7e1033
        token: xiaoligongzuoshi
        aesKey: xiaoligongzuoshi
        msgDataFormat: JSON