server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.43.168:3306/qing
    username: root
    password: abC123456!

  redis:
    host: 8.130.43.168
    port: 6379
    password: 123456
    database: 0



wx:
  miniapp:
    configs:
      - appid: wx4e7262cc3da38892
        secret: 8fc162f01a1cf1745eeccfe8a8089858
        token: xiaoligongzuoshi
        aesKey: xiaoligongzuoshi
        msgDataFormat: JSON