##上线环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##配置自己的数据库密码和账号以及地址
    url:
    username:
    password:
  ##配置自己的redis密码和账号,地址以及数据库
  redis:
    host:
    port:
    password:
    database:
  ##配置自己的MongoDB密码和账号,地址以及数据库
  data:
    mongodb:
      host:
      port:
      database:
      password:
      username:


##开发服务器
server:
  port: 443
  ssl:
    key-store: ##classpath: 域名证书
    key-store-password: ##证书密码
    key-store-type: PKCS12

##对象存储配置(开发服务器minio地址)
oss:
  endpoint: ##Minio地址
  access-key: ##Minio Ak
  secret-key: ##Minio Sk