server:
  port: 8089
#  ssl:
#    key-store: classpath:cuuemo.cn.pfx
#    key-store-password: 8omav52gx17g72
#    key-store-type: PKCS12
#server:
#  port: 443
#  ssl:
#    key-store: classpath:www.xiaoligongzuoshi.top.pfx
#    key-store-password: 6jramg04
#    key-store-type: PKCS12


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://8.130.43.168:3306/qing
#    username: root
#    password: abC123456!
#
#  redis:
#    host: 8.130.43.168
#    port: 6379
#    password: 123456
#    database: 0
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.67.226:3306/qing
    username: xiaoli
    password: abC123456@

  redis:
    host: 114.132.67.226
    port: 6379
    password: abC123456@
    database: 0

#wx:
#  miniapp:
#    configs:
#      - appid: wx4e7262cc3da38892
#        secret: 8fc162f01a1cf1745eeccfe8a8089858
#        token: xiaoligongzuoshi
#        aesKey: xiaoligongzuoshi
#        msgDataFormat: JSON
#
#  pay:
#    appId: wx4e7262cc3da38892
#    mchId: 1633635850
#    mchKey: 80fd6711682fa5a3ffa9abd53981c368
#    keyPath: classpath:apiclient_cert.p12

wx:
  miniapp:
    configs:
      - appid: wxb53fb342651c6c2a
        secret: 6b9e4c65c7e531285e98e894b39afe6a
        token: xiaoligongzuoshi
        aesKey: xiaoligongzuoshi
        msgDataFormat: JSON

  pay:
    appId: wxb53fb342651c6c2a
    mchId: 1652632090
    mchKey: on8rr08djaowyr9hyqfivsu1taxcpjs9
    keyPath: classpath:new.p12
