##本地环境配置(全部配置都是local)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qing
    username: ## mysql 用户名
    password:   ## mysql 密码
  ##配置自己的redi密码和账号,地址以及数据库
  redis:
    host: localhost
    port: 6389
    password:
    database: 0
  data:
    ##配置自己的MongoDB密码和账号,地址以及数据库
    mongodb:
      host: localhost
      port: 27017
      database:
      password:
      username:

##端口8089
server:
  port: 8089

##对象存储配置
oss:
  endpoint: ##Minio 地址
  access-key: ##Minio AK密钥
  secret-key: ## Minio SK密钥