spring:
  profiles:
    ##运行环境
    active: local-dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

##微信小程序配置(微信公众平台获取)
wx:
  miniapp:
    configs:
      - appid:
        secret:
        token:
        aesKey:
        msgDataFormat: JSON
##支付配置(微信支付控制台获取)
  pay:
    appId:
    mchId:
    mchKey:
      ##支付证书,微信平台获取
    keyPath:
##支付成功后回调配置(注意域名可能会更新)
callback:
  ##支付成功回调地址
  success-address:
    ##退款成功回调地址
  refund-address:

##课程表获取配置
course:
  ##课程表地址
  course-address:
##学生认证配置
verify-address:
  ##认证地址接口
  verify-address:
  ##认证地址接口
  verify-address-new:
